// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAATwfCnaf6D95wKcjyGaU-HOkcUo4IRxs',
    appId: '1:335506891082:android:275613bcaa53d4597661b3',
    messagingSenderId: '335506891082',
    projectId: 'gedi-8494a',
    storageBucket: 'gedi-8494a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfqL0AbU-oVVaVnO0Z7-gQRNhg-1BB8DM',
    appId: '1:335506891082:ios:6677a85dae0ad38a7661b3',
    messagingSenderId: '335506891082',
    projectId: 'gedi-8494a',
    storageBucket: 'gedi-8494a.appspot.com',
    iosClientId: '335506891082-vohpsn8k9m0sckui4a5k5csnuvhp67s2.apps.googleusercontent.com',
    iosBundleId: 'com.dadaren.gedi',
  );
}
